[build]
  publish = "dist"
  command = "yarn run generate && yarn run build:api"
  functions = "./functions"
[build.environment]
  NODE_VERSION = "12" 
  YARN_FLAGS = "--no-ignore-optional"
[template.environment]
API_URL = "https://wonderful-volhard-8bdfc8.netlify.app/"
  SENDGRID_API_KEY = "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"
  SENDGRID_WELCOME_SENDER_EMAIL = "publishing@knighttimesnews.com"
  SENDGRID_WELCOME_SENDER_NAME = "Publishing Knight Times News"
  SENDGRID_WELCOME_TEMPLATE_ID = "Sendgrid Welcome Email Template ID"